export const UserData = [
    {
        id:"1",
        username:"Sohil",
        email:"shlkoitiya@gmail.com",
        password:123
    },
    {
        id:"2",
        username:"Priti",
        email:"priti@gmail.com",
        password:1234
    },
    {
        id:"3",
        username:"ayan",
        email:"ayan@gmail.com",
        password:12345
    }
]